name: MultiSpawn
version: '${project.version}'
main: cn.paper_card.multi_spawn.MultiSpawn
api-version: '1.20'
author: Paper99
folia-supported: true

commands:
  spawn:
    permission: multi-spawn.command.spawn

  multi-spawn:
    permission: multi-spawn.command

permissions:
  multi-spawn.command.spawn:
    default: true

  multi-spawn.command:
    default: op
